var a=100 , b=20;
var add,sub,mul,div,mod;
add=a+b;
sub=a-b;
mul=a*b;
div=a/b;
mod=a%b;

document.write("<hr>");
document.write("<hr>");
document.write(add);
document.write("<br>");
document.write(sub);
document.write("<br>");
document.write(mul);
document.write("<br>");
document.write(div);
document.write("<br>");
document.write(mod);
document.write("<hr>");

document.write("addition of two number= "+add);
document.write("<br>");
document.write("subtraction of two number= "+sub);
document.write("<br>");
document.write("multiplication of two number= "+mul);
document.write("<br>");
document.write("division of two number= "+div);
document.write("<br>");
document.write("modulous of two number= "+mod);
document.write("<hr>");